### ISSUE TITLE
Map editor

### ISSUE THREAD

**Issue by steadramon** [Veradictus/Kaetram-ES6#1]
Hi there,

I think I've tracked you down from the BQ discussion on another project written with phaser (perhaps not!) 

Getting to grips with the code and layout in hope of spawning a game of my own from this excellent base.

Question - is there a program I can use to open and edit the map json files, Tiled doesn't like the format?

Thanks!

**Comment by Veradictus** [comment]
This version uses custom image assets for the current expansion. I am only releasing work that I have made myself, and therefore can't release licensed assets from other creators.

The map at the moment is really primarily for development, so you will not be getting much even if you could open it. I suggest just finding yourself some assets, and starting a new Tiled map from scratch.
